config:
  request:
    iplimit:
      apis: /api/user/register/
      intervalMinutes: 1
      maxRequestCount: 6

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   mail:
    host: smtp.qq.com #发送邮件服务器
    username: 517309804@qq.com #发送邮件的邮箱地址
    password:  awznvjqobwkkbjfi #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 587
    from: 517309804@qq.com # 发送邮件的地址，和上面username一致
